### PR TITLE
Add tests to Test PXC and PS Docker image with 8.0/latest/upstream/debug tags

### PR DESCRIPTION
**Pull request by kaushikpuneet07**
Recently we observed one issue with PXC 8.0 docker image . Image was not updated with latest PXC version.

Test are added to check pxc version of PXC docker image with tag as 8.0. As this image is only available in percona repo so for perconalab it is skipped.

### CODE REVIEW

**Comment by kaushikpuneet07** [comment]
Successfull job link with perconalab : https://pxc.cd.percona.com/job/qa-docker-image/208/
Successfill job link with percona : https://pxc.cd.percona.com/job/qa-docker-image/207/

**Review by eleo007 — COMMENTED** [review]
Hi, 
I would add checks for all the tags we have in Percona:
- latest
- 8.0 (major)
- 8.0.33 (major-upstream)
- 8.0.33-25.1 we already have (major with Percona ver)

**Comment by kaushikpuneet07** [comment]
Updated all mentioned tags 
Successfull job : https://pxc.cd.percona.com/job/qa-docker-image/212/console

**Review by eleo007 — APPROVED** [review]

**Review by eleo007 — APPROVED** [review]

**Comment by kaushikpuneet07** [comment]
Added tests for latest , Major version , upstream in PS docker job also 
Successful job after updates : https://ps80.cd.percona.com/view/PS-Docker-jobs/job/test-ps-docker-image/38/

**Pull request merged**
